/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare class Simulator {
  constructor()
  simulate(userAddress: string, tokenInAddress: string, toAddress: string, calldata: string, chainId: number, rpcUrl: string, amountIn: string): Promise<void>
}
