/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RpcSuccess {
  status: 'rpc_success'
  output: string
}
export interface RpcRevert {
  status: 'rpc_revert'
  revertReason: string
}
export interface RpcFailedRevmSuccess {
  status: 'rpc_failed_revm_success'
  output: string
  rpcError: string
}
export interface RpcFailedRevmRevert {
  status: 'rpc_failed_revm_revert'
  rpcError: string
  executionResult: string
}
export interface BothFailed {
  status: 'both_failed'
  rpcError: string
  revmError: string
}
export interface Error {
  status: 'error'
  error: string
}
export declare class Simulator {
  constructor()
  simulate(userAddress: string, tokenInAddress: string, toAddress: string, calldata: string, chainId: number, rpcUrl: string, amountIn: string): Promise<RpcSuccess | RpcRevert | RpcFailedRevmSuccess | RpcFailedRevmRevert | BothFailed | Error>
}
