/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function simulate(userAddress: string, tokenInAddress: string, toAddress: string, calldata: string, rpcUrl: string, amountIn: string): void
